image: gradle:alpine

default:
  tags:
    - shelllocal


stages:
  - tests
  - allure


SMOKE TESTS:
  stage: tests
  allow_failure: true
  script:
    - echo "Запуск тестов"
    - gradle test -Dtags=Smoke
  artifacts:
    when: always
    paths:
     - build/allure-results


ALLURE:
  stage: allure
  script:
    - gradle allureReport
    - echo "Allure report is here - http://localhost:63342/SelenideTestingNewGradle/build/reports/allure-report/allureReport/index.html?_ijt=otfao76sodnuj65itka2sema70&_ij_reload=RELOAD_ON_SAVE"
  artifacts:
    when: always
    paths:
      - build/reports/allure-report/allureReport/*