image: gradle:alpine

default:
  tags:
    - shelllocal


stages:
  - tests
  - allure


SMOKE TESTS:
  stage: tests
  allow_failure: true
  script:
    - echo "Запуск тестов"
    - gradle clean test -Dtags=Smoke
  artifacts:
    when: always
    paths:
     - build/allure-results


ALLURE:
  stage: allure
  script:
    - gradle allureServe
    - echo "Allure report is here - http://192.168.108.30:53266/"
  artifacts:
    when: always
    paths:
      - build/reports/allure-report/allureReport/*