image: gradle:alpine
default:
  tags:
    - shelllocal

stages:
  - test
smoke tests with Allure:
  stage: test
  script:
    - ./gradlew test
  after_script:
    - ./gradlew allureServe
  artifacts:
    when: always
    paths:
     - build/reports/allure-report/allureReport/*

