image: gradle:alpine

default:
  tags:
    - shelllocal


stages:
  - tests
  - allure


TESTS:
  stage: tests
  allow_failure: true
  script:
    - echo "Запуск тестов"
    - gradle test
  artifacts:
    when: always
    paths:
     - build/allure-results


ALLURE:
  stage: allure
  script:
    - gradle allureServe
    - echo "Allure report is here - "
  artifacts:
    when: always
    paths:
      - build/reports/allure-report/allureReport/*