image: gradle:alpine
default:
  tags:
    - shelllocal


stages:
  - ui
  - allure


UI tests:
  stage: ui
  allow_failure: true
  script:
    - ./gradlew test
  artifacts:
    when: always
    paths:
     - build/allure-results*


Allure report:
  stage: allure
  script:
    - ./gradlew allureServe
  artifacts:
    when: always
    paths:
      - build/reports/allure-report/allureReport/*